### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Movisivi** [ThijmenDam/BarTranslate#1]
title.

**Comment by ThijmenDam** [comment]
Hi @Movisivi! Top priority issue indeed :-)

**Comment by ThijmenDam** [comment]
Currently integrating dark mode in the app! Besides the app itself, the translator webpages have to be converted to a dark theme using CSS as well. I created a basic CSS "dark theme" for [translate.google.com](translate.google.com) already (see CSS snippet below). If anyone has a better snippet available let me know!

`.feedback-link,
.gp-footer,
.morebutton,
.notification-area,
.res-tts,
.source-footer,
.source-input-tools,
.starbutton,
header,
nav,
.a88hkc,
.FFpbKc,
.VjFXz {
    display: none !important;
}
div.source-input {
    border-bottom: 1px solid #eee !important;
    padding-bottom: 16px !important;
    min-height: 100px !important;
}
.frame {
    height: 100% !important;
}
.tlid-source-transliteration-container {
    margin: 0 !important;
}
.source-footer-wrap {
    display: none !important;
}
div#spelling-correction {
    margin-bottom: 0 !important;
    position: absolute !important;
    bottom: 0 !important;
}
.I87fLc.XzOhkf {
    background: #2c2c2e;
}
.ccvoYb {
    background-color: #2c2c2e;
}
.q7sDqe:not(:disabled),
.q7sDqe:not(:disabled) .VfPpkd-kBDsod {
    color: #fdffff;
}
body {
    color: #fdffff;
}
.RstnCb {
    background: #2c2c2e;
}
.KskmCc {
    background-color: #2c2c2e;
    color: #fdffff;
}
.ordo2 {
    color: #fdffff;
}
.rT1Yue {
    border-bottom: 1px solid #48484a;
}
.er8xn {
    color: #fdffff;
}
.RvYhPd {
    background-color: #1c1c1e;
}
.ooArgc:focus {
    background-color: #2c2c2e;
}
.VhOj3e {
    color: #fdffff;
}
.P6w8m.BDJ8fb:not(.Jj6Lae) {
    background: #185abc;
}
.ooArgc {
    color: #fdffff !important;
}
.Tht3fc > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(3) {
    background-color: #2c2c2e;
}
.Tht3fc > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > input:nth-child(2) {
    color: #fdffff;
}
.Tht3fc > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) {
    background-color: #2c2c2e;
}
.aCQag > c-wiz:nth-child(1) {
    background-color: #1c1c1e;
}
h3 {
    color: #fdffff !important;
}
span {
    color: #fdffff !important;
}
.DlHcnf > div:nth-child(2) > div:nth-child(1) > div:nth-child(3) {
    background-color: #1c1c1e;
}

`

**Comment by ThijmenDam** [comment]
As per the conversion to Swift (#24), dark mode has been partially implemented, i.e. all native GUI elements adapt to the system's current setting . However, no dark mode CSS is yet injected, meaning the Google Translate and DeepL pages are still only available in light mode.

**Comment by Movisivi** [comment]
Holy hell, I don't even have a Mac anymore and this issue still isn't closed.
