### ISSUE TITLE
[Feature Request] Support for Deepl

### ISSUE THREAD

**Issue by zenminimalist** [ThijmenDam/BarTranslate#13]
Considered one of the best translator (even better than Google) - Deepl. Adding support for this would be mind-blowing. Also has an [API](https://www.deepl.com/pro-api?cta=header-pro-api/). The free version has come cut offs, but never hit them.

**Comment by ThijmenDam** [comment]
Great suggestion.

BarTranslate embeds an (altered) webview, so usage of their API won't even be necessary (but thanks for thinking along!). I'll look into it, though implementation may take a while - at this moment I do not have much free time.

**Comment by zenminimalist** [comment]
Ah, that makes sense. Webview is easier I guess : ) Take you time with your app - that is great already.

**Comment by ThijmenDam** [comment]
Hi @zenminimalist, you can expect the DeepL release tomorrow 🙂

**Comment by ThijmenDam** [comment]
BarTranslate now supports DeepL!

You can find the latest release here: https://github.com/ThijmenDam/BarTranslate/releases/tag/v0.5.0
