### ISSUE TITLE
Important note regarding development :-)

### ISSUE THREAD

**Issue by ThijmenDam** [ThijmenDam/BarTranslate#2]
Hey everyone,

First a thanks that you're reading this. Really appreciate you looking into BarTranslate!

I initially developed BarTranslate to fill a personal need of mine. When a few friends also stated their interest, I decided to make it publicly available for everyone to see. Basic functions are there, and I have plenty of ideas (also thanks to you!) that will be implemented in the future.

On to the note: my life is very, very busy at this moment due to university/work/band. Because of this, new features might take a while to implement. Just know that they will, eventually :-)

**Comment by uguraktas** [comment]
How would you like to make opensource this project and share the source code? So, everyone can contribute.

**Comment by ThijmenDam** [comment]
@uguraktas I will. The app is currently written in Swift, but as we speak I work on converting it to an Electron app (TypeScript/React) to allow for quicker development and support for Windows and Linux. I'll publish the codebase as soon as I have an MVP.

**Comment by ThijmenDam** [comment]
@uguraktas BarTranslate is now [open source](https://github.com/ThijmenDam/BarTranslate/discussions/4)!
