### ISSUE TITLE
"BarTranslate is broken and can not be opened" M1 Air

### ISSUE THREAD

**Issue by Brin-o** [ThijmenDam/BarTranslate#21]
Hi!

This is on my M1 Air, with gatekeeper disabled.

<img width="765" alt="image" src="https://user-images.githubusercontent.com/49071768/230707390-05dfae8d-88bf-4fc0-a17b-6e61535a52ba.png">

**Comment by ThijmenDam** [comment]
What macOS version are you on @Brin-o?

**Comment by ThickDrinkLots** [comment]
I have the same issue. My MacOS version is `13.3.1`

**Comment by ThijmenDam** [comment]
Does the non-silicon version of the app work via Rosetta, or are both files damaged?

The last time this happened it had something to do with the packager using outdated dependencies I think. I have some time available this week, so expect a release after the weekend if that's the culprit.

**Comment by ThickDrinkLots** [comment]
x86 version works.

**Comment by nilesh** [comment]
x64 version is now broken for me on Apple Silicon. So none of the versions work. 
<img width="352" alt="image" src="https://github.com/ThijmenDam/BarTranslate/assets/4850/9d3a49b0-5f5f-4e4f-90f5-f147f00e431e">

**Comment by gabrielwhite** [comment]
> x64 version is now broken for me on Apple Silicon. So none of the versions work. <img alt="image" width="352" src="https://user-images.githubusercontent.com/4850/241937474-9d3a49b0-5f5f-4e4f-90f5-f147f00e431e.png">

Try right-clicking on the app and selecting "Open" - you should get a different dialog box.

Any updates on this issue? I have same problem with ARM version on 13.4.1

**Comment by ThijmenDam** [comment]
@gabrielwhite I will release the native version of the app (i.e. written in Swift) this week. You could perhaps use the version I posted in a previous comment in this thread until then.

**Comment by markbellus** [comment]
@ThijmenDam hey mate, may I ask if has it been released? or where can I actually find it?

**Comment by ThijmenDam** [comment]
Hi @markbellus, the first native Swift version is not yet released, but development is finished. As I am currently on holiday I won't be able to publish it yet, but I'll do that ASAP when I'm home. Keep an eye on the releases page!

**Comment by markbellus** [comment]
@ThijmenDam Thank you for your kind reply, enjoy your time man. Will keep on eye on it, thanks for the information.

**Comment by ThijmenDam** [comment]
@markbellus just letting you know that I haven't forgotten about this. There is a lot going on right now for me, so I haven't found the time to publish the release. However, I plan to do so this Saturday.

**Comment by markbellus** [comment]
@ThijmenDam Man, no need to worry. Just take your time and get things done. Huge thanks for all the effort you put in.

**Comment by ThijmenDam** [comment]
The native macOS version of BarTranslate has now been released! See #24. 

@markbellus could you let me know if this has resolved the problem for you? If so, I'll close this issue.

**Comment by markbellus** [comment]
@ThijmenDam Thanks man! Now it's working perfectly, sure you can close it. Really appreciate your work! Wish you a great weekend.

**Comment by ThijmenDam** [comment]
@markbellus that's great to hear! Thank you, have a good weekend too!
