### ISSUE TITLE
Black/White icon for status bar

### ISSUE THREAD

**Issue by denbue** [ThijmenDam/BarTranslate#26]
Really like the new release! It's indeed a minor request, but any chance the status bar icon could be be black (light mode) or white (dark mode)? Somehow it's the only colored icon in my status bar..

<img width="159" alt="image" src="https://github.com/ThijmenDam/BarTranslate/assets/2946670/9e3ad27e-d5be-41d7-9916-0bf0881f14b3">

**Comment by ThijmenDam** [comment]
Hi @denbue, good suggestion, thanks. I'll add it to the list with planned features. Also, glad to hear you like the new release!
