### ISSUE TITLE
“BarTranslate.app” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by aetrnm** [ThijmenDam/BarTranslate#30]
“BarTranslate.app” can’t be opened because Apple cannot check it for malicious software.
It asks me to contact the developer
any ideas?

M2 Air Sonoma 14.0

**Comment by ThijmenDam** [comment]
Hi @aetrnm! The message you are seeing is not directly related to BarTranslate, and can be circumvented easily.

Could you reproduce [steps described on the official Apple Support page](https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac), and let me know if that worked out for you?

**Comment by aetrnm** [comment]
@ThijmenDam it's fine now, thanks!
