### ISSUE TITLE
Certificate revoked and notarization not stapled

### ISSUE THREAD

**Issue by wkneppersR3** [ThijmenDam/BarTranslate#34]
While installing this app, Gatekeeper doesn't allow me to open the application. Both the certificate is revoked, and the notarization isn't stapled.

**Comment by ThijmenDam** [comment]
@wkneppersR3 does [this](https://support.apple.com/en-hk/guide/mac-help/mh40616/mac) resolve your issue?

**Comment by wkneppersR3** [comment]
It will resolve the issue, but it's not the way I'd like to handle it. Are you planning on notarization?

**Comment by ThijmenDam** [comment]
@wkneppersR3 eventually, yes, though I'm afraid that may take a few weeks because I don't have much time on my hands right now.
