### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by elliedaladie** [ThijmenDam/BarTranslate#48]
Very cool app! Can you explain how to set the keyboard shortcuts to swap the languages and set the languages (as noted in v0.4.0 release notes)? When I open the options tab, there is only the ability to enter a keyboard shortcut to open the app, nothing about the other shortcuts you mentioned that would swap languages or set languages. Also, when I set the shortcut to activate the app in the menubar, it doesn't seem to do anything. I'm on an M1 MBP and Sonoma. I'm on v1.1 of your app. Thx!

**Comment by ThijmenDam** [comment]
Hi @elliedaladie, I'm glad you like BarTranslate! 

Concerning your issue, it is not possible (yet) to swap languages with a keyboard shortcut. The reason you used to be able to do this, is that the app has been rewritten from scratch in Swift (for a whole lot of reasons), and after the rewrite I have not taken the time yet to implement this feature.

**Comment by elliedaladie** [comment]
Thanks so much for getting back to me. Understood regarding the swapping of languages. I'm assuming that is the same with setting the languages too. What about my inability to activate it (pull it down from the toolbar) via a keyboard shortcut once it's been launched? Do you think that is also a regression from the Swift rewrite, or just a bug (or maybe something on my side)? Thanks

**Comment by ThijmenDam** [comment]
@elliedaladie do you use the latest version of the app, so version 1.1? 

Opening and closing via a keyboard shortcut works on my machine (2016 MacBook Pro, Monterey 12.7.6). If it doesn't on your machine, could you share some information about your device, and which exact shortcuts you use?

**Comment by ThijmenDam** [comment]
No further response - issue closed.
