### ISSUE TITLE
Mac OS Seqouia will not allow installing either v1.0 or v1.1.0

### ISSUE THREAD

**Issue by OmriGalai** [ThijmenDam/BarTranslate#49]
Hi there,
I'm not well versed in opening Github issues, so do let me know if you need extra information.
In any case, the following happens on Sequoia 15.0 with BarTranslate v1.1 and v1.0 respectively:
<img width="258" alt="Screenshot 2024-09-11 at 14 48 21" src="https://github.com/user-attachments/assets/b34865d1-0bf5-4853-a2b0-ee991588e628">
<img width="258" alt="Screenshot 2024-09-11 at 14 48 57" src="https://github.com/user-attachments/assets/9c4549b5-8423-4db9-9ed1-8c1d69febbe7">

**Comment by ThijmenDam** [comment]
After opening BarTranslate, go to Settings, Privacy & Security, scroll down and click "Open anyway". Does this work for you?

**Comment by OmriGalai** [comment]
It worked, thanks!
