### ISSUE TITLE
[Feature Request] Autofocus the windows when toggled

### ISSUE THREAD

**Issue by Write** [ThijmenDam/BarTranslate#6]
When the icon is clicked in the menu-bar, or invoked trough the keyboard shortcut, it would be great if the popup windows would be directly focused so we can write / copy right away.

**Comment by ThijmenDam** [comment]
Great suggestion, should be not too difficult to implement (properly). Will take a look at it tonight or tomorrow.

**Comment by ThijmenDam** [comment]
@Write consider it done!

In [release 0.2.2](https://github.com/ThijmenDam/BarTranslate/releases/tag/0.2.2) the translate input is automatically focused whenever the application is shown.
