### ISSUE TITLE
[Feature Request] Apple Silicon Support

### ISSUE THREAD

**Issue by VladislavSmolyanoy** [ThijmenDam/BarTranslate#7]

**Comment by Write** [comment]
I'm running it fine on my M1 ? Am I missing something ?

**Comment by ThijmenDam** [comment]
@VladislavSmolyanoy do you mean native Apple Silicon support? I don't think this architecture is supported by Electron. That said, running the `x64` version via Rosetta works flawlessly on my M1 MacBook that I use for work.

**Comment by VladislavSmolyanoy** [comment]
My main issue is the impact that rosetta has on battery life.
Even small rosetta apps can dramatically decrease the potential battery life

**Comment by Write** [comment]
It seems Electron does indeed support Apple Silicon natively since v11.0 ?

**Comment by ThijmenDam** [comment]
@Write Yes you are right. I'll look into it.
